"""initial

Revision ID: 13a7c9b2275a
Revises: 
Create Date: 2026-05-28 20:50:06.628183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a7c9b2275a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='grants_svc'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='grants_svc'
    )
    op.create_table('grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('grantor_id', sa.UUID(), nullable=False),
    sa.Column('grantee_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['grants_svc.documents.id'], ),
    sa.ForeignKeyConstraint(['grantee_id'], ['grants_svc.users.id'], ),
    sa.ForeignKeyConstraint(['grantor_id'], ['grants_svc.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='grants_svc'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grants', schema='grants_svc')
    op.drop_table('users', schema='grants_svc')
    op.drop_table('documents', schema='grants_svc')
    # ### end Alembic commands ###
